[build]
  command = "npm run build" 
  publish = "my-portfolio/build" 
  functions = "serverless-functions"

[[redirects]]
  from = "/submit-form"
  to = "/.netlify/functions/submit-form"
  status = 308